functionsDirectory = "C:\\Users\\steve\\Documents\\skyesoft\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\steve\\Documents\\skyesoft"
publishOrigin = "ui"
functions = "C:\\Users\\steve\\Documents\\skyesoft\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]