---
deployment:
  tasks:
    # 1. Clean the cPanel-managed repo
    - cd /home/notyou64/skyesoft && git reset --hard HEAD && git clean -fd

    # 2. Set deployment path
    - export DEPLOYPATH=/home/notyou64/public_html/skyesoft

    # 3. Copy files (use cp instead of rsync for compatibility)
    - /bin/cp -R ./ $DEPLOYPATH
