---
deployment:
  tasks:
    # 1. Clean the cPanel-managed repo
    - cd /home/notyou64/skyesoft && git reset --hard HEAD && git clean -fd

    # 2. Set deployment path
    - export DEPLOYPATH=/home/notyou64/public_html/skyesoft

    # 3. Sync files (mirror with delete, exclude .git and this yaml file)
    - rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH
