<?php
declare(strict_types=1);

// ======================================================================
//  Skyesoft — generateDocument.php
//  Tier: 3 — Document Assembly
//  PHP 8.3+ • Strict Typing
//
//  Responsibility:
//   • Read a canonical document record (e.g. audit, report, sheet)
//   • Apply the Document Standard layout
//   • Inject content into the approved HTML template
//   • Produce a render-ready HTML document
//
//  Forbidden:
//   • NO Codex mutation
//   • NO doctrine interpretation
//   • NO layout logic outside the template
//   • NO direct PDF rendering
// ======================================================================

header("Content-Type: application/json; charset=UTF-8");

#region SECTION 0 — Configuration

$templatePath = __DIR__ . '/../documents/templates/documentTemplate.html';
$outputDir    = __DIR__ . '/../documents/output/';

#endregion

#region SECTION 1 — Fail Handler

function fail(string $msg): never {
    echo json_encode([
        "success" => false,
        "role"    => "documentGenerator",
        "error"   => "❌ {$msg}"
    ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}

#endregion

#region SECTION 2 — Input Load

// Example source document (audit); later becomes parameterized
$sourcePath = __DIR__ . '/../codex/meta/codexAudit.json';

if (!file_exists($sourcePath)) {
    fail("Source document not found.");
}

$document = json_decode(file_get_contents($sourcePath), true);
if (!is_array($document)) {
    fail("Invalid document JSON.");
}

#endregion

#region SECTION 3 — Template Load

if (!file_exists($templatePath)) {
    fail("Document template not found.");
}

$template = file_get_contents($templatePath);

#endregion

#region SECTION 4 — Header / Footer Assembly (Non-Governing)

$headerContent =
    "<strong>{$document['documentMeta']['title']}</strong>";

$footerContent =
    "Generated by Skyesoft • {$document['auditDate']}";

#endregion

#region SECTION 5 — Body Assembly (Narrative Only)

$body = '';

if (!isset($document['reportNarrative'])) {
    fail("Document contains no renderable narrative sections.");
}

foreach ($document['reportNarrative'] as $sectionKey => $section) {

    $body .= "<div class='section'>";

    $body .= "<div class='section-header'>";
    $body .= "<span class='icon'>[{$section['icon']}]</span>";
    $body .= "<span>{$sectionKey}</span>";
    $body .= "</div>";

    switch ($section['contentFormat']) {

        case 'paragraphs':
            foreach ($section['text'] as $paragraph) {
                $body .= "<p>{$paragraph}</p>";
            }
            break;

        case 'paragraph':
            $body .= "<p>{$section['text']}</p>";
            break;

        case 'bullets':
            $body .= "<ul>";
            foreach ($section['items'] as $item) {
                $body .= "<li>{$item}</li>";
            }
            $body .= "</ul>";
            break;
    }

    $body .= "</div>";
}

#endregion

#region SECTION 6 — Template Injection

$html = str_replace(
    ['{{documentTitle}}', '{{headerContent}}', '{{footerContent}}', '{{documentBody}}'],
    [
        $document['documentMeta']['title'],
        $headerContent,
        $footerContent,
        $body
    ],
    $template
);

#endregion

#region SECTION 7 — Output Write

if (!is_dir($outputDir)) {
    mkdir($outputDir, 0755, true);
}

$outputPath = $outputDir . 'codexAudit.html';

file_put_contents($outputPath, $html);

#endregion

#region SECTION 8 — Completion Signal

echo json_encode([
    "success" => true,
    "role"    => "documentGenerator",
    "message" => "✔ Document generated",
    "path"    => $outputPath
], JSON_PRETTY_PRINT);

#endregion