<?php
require_once(__DIR__ . '/../vendor/fpdf/fpdf.php'); // adjust path if needed

// Read JSON POST
$raw = file_get_contents("php://input");
$data = json_decode($raw, true);

// Fallback if no data
if (!$data) {
    echo json_encode([
        "error" => true,
        "message" => "No input data provided."
    ]);
    exit;
}

// Extract inputs
$inputs      = isset($data['inputs']) ? $data['inputs'] : array();
$disclaimers = isset($data['disclaimers']['Zoning Report']) ? $data['disclaimers']['Zoning Report'] : array();
$projectName = isset($inputs['address']) ? $inputs['address'] : "Zoning Report";

// ✅ Set file save path
$reportsDir = __DIR__ . '/../reports/';
if (!is_dir($reportsDir)) {
    mkdir($reportsDir, 0775, true);
}
$filename = 'ZoningReport_' . preg_replace('/[^A-Za-z0-9]/', '_', $projectName) . '_' . date('Ymd_His') . '.pdf';
$filepath = $reportsDir . $filename;
$pdfLink  = '/reports/' . $filename; // relative link

// ✅ Create PDF
$pdf = new FPDF();
$pdf->AddPage();

// Header
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'Zoning Report',0,1,'C');
$pdf->Ln(5);

// Project / Address
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,10,'Project: ' . $projectName,0,1);
$pdf->Ln(2);

// Inputs summary
$pdf->SetFont('Arial','',10);
foreach ($inputs as $key => $val) {
    if (is_array($val)) {
        $val = json_encode($val);
    }
    $pdf->MultiCell(0,6, ucfirst($key) . ": " . $val);
    $pdf->Ln(1);
}

// Disclaimers
$pdf->Ln(5);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,10,'Disclaimers:',0,1);

$pdf->SetFont('Arial','',9);
foreach ($disclaimers as $d) {
    $pdf->MultiCell(0,5,"- " . $d);
    $pdf->Ln(1);
}

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Arial','I',8);
$pdf->Cell(0,10,'Generated by Skyebot • ' . date('Y-m-d H:i'),0,0,'C');

// ✅ Save PDF
$pdf->Output('F', $filepath);

// ✅ Return JSON with link
header('Content-Type: application/json');
echo json_encode([
    "error" => false,
    "pdfLink" => $pdfLink,
    "message" => "Zoning Report PDF generated."
], JSON_PRETTY_PRINT);
